### ISSUE TITLE
How to write a test ?

### ISSUE THREAD

**Issue by nitinsurana** [resthub/resthub-spring-stack#251]
```
import com.nitinsurana.model.DataBean;
import com.nitinsurana.repository.DataBeanRepository;
import org.resthub.test.AbstractTest;
import org.testng.annotations.Test;
import javax.inject.Inject;
import javax.inject.Named;

/**
 * Created by nitin on 13-11-2014.
 */
public class RepositoryTest extends AbstractTest {

    @Inject
    private DataBeanRepository dataBeanRepository;

    @Test
    public void  testRepositorySave(){
        System.out.println("Does it work");
        System.out.println(dataBeanRepository);
//        DataBean bean = new DataBean();
//        bean.setPrice(123.23);
//        dataBeanRepository.save(bean);
    }
}
```

Above threw the following exception : 

org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'mongoTemplate' is defined
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:660) ~[spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1157) ~[spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:280) ~[spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193) ~[spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328) ~[spring-beans-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    ... 79 common frames omitted
Wrapped by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataBeanRepository': Cannot resolve reference to bean 'mongoTemplate' while setting bean property 'mongoOperations'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'mongoTemplate' is defined

**Comment by nitinsurana** [comment]
Tried

`public class RepositoryTest extends AbstractTransactionalTest {`

still didn't worked, same error.

**Comment by bmeurant** [comment]
Really not convinced that this is a Resthub issue. 

Thank you to provide a complete reproducible test case if you are sure this is related to Resthub.
