### ISSUE TITLE
Conflict between Resthub-test and Spring JUnit in AbstractTransactionalTest?

### ISSUE THREAD

**Issue by Jcolin** [resthub/resthub-spring-stack#53]
When running a unit test verifying the throw of IllegalArgumentException (extending RuntimeException), some strange behaviour appears during the rollback of the transaction.

My class under test :

```
package net.awl.uts.sample;

import javax.inject.Named;

import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;


@Named("sampleService")
@Transactional(propagation = Propagation.REQUIRED, readOnly = true)
public class SampleService {

    @Transactional(readOnly=false)
    public void sampleMethod(Object sampleParameter) {
        Assert.notNull(sampleParameter, "parameter must not be null");
    }
}
```

My test case :

```
package net.awl.uts.sample.test;


import net.awl.uts.sample.SampleService;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.resthub.core.test.AbstractTransactionalTest;
import org.resthub.test.dbunit.annotation.DbUnitSpringJUnit4ClassRunner;
import org.springframework.beans.factory.annotation.Autowired;


@RunWith(DbUnitSpringJUnit4ClassRunner.class)
public class SampleServiceTestTransactional extends AbstractTransactionalTest{

    @Autowired
    SampleService sampleService;

    @Test(expected=IllegalArgumentException.class)
    public void testSampleMethod() {
        sampleService.sampleMethod(null);
    }
}
```

And the Stacktrace obtained :

17:07:03 -  WARN - org.springframework.test.context.TestContextManager.afterTestMethod:409 - Caught exception while allowing TestExecutionListener [org.springframework.test.context.transaction.TransactionalTestExecutionListener@5ae6c6d7] to process 'after' execution for test: method [public void net.awl.uts.sample.test.SampleServiceTestTransactional.testSampleMethod()], instance [net.awl.uts.sample.test.SampleServiceTestTransactional@65087be0], exception [null]
org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Transaction marked as rollbackOnly
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:476)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener$TransactionContext.endTransaction(TransactionalTestExecutionListener.java:515)
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener.endTransaction(TransactionalTestExecutionListener.java:290)
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener.afterTestMethod(TransactionalTestExecutionListener.java:183)
    at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:406)
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:90)
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
    at org.resthub.test.dbunit.annotation.DbUnitSpringJUnit4ClassRunner.runChild(DbUnitSpringJUnit4ClassRunner.java:16)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: javax.persistence.RollbackException: Transaction marked as rollbackOnly
    at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:73)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:467)
    ... 25 more

When extending AbstractTransactionAwareTest in my test case, the test works just fine.

```
package net.awl.uts.sample.test;


import net.awl.uts.sample.SampleService;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.resthub.core.test.AbstractTransactionAwareTest;
import org.resthub.test.dbunit.annotation.DbUnitSpringJUnit4ClassRunner;
import org.springframework.beans.factory.annotation.Autowired;


@RunWith(DbUnitSpringJUnit4ClassRunner.class)
public class SampleServiceTestTransactionAware extends AbstractTransactionAwareTest{

    @Autowired
    SampleService sampleService;

    @Test(expected=IllegalArgumentException.class)
    public void testSampleMethod() {
        sampleService.sampleMethod(null);
    }
}
```

**Comment by sdeleuze** [comment]
It should be fixed in RESThub 2 since we now use TestNG based tests.
